<?php

namespace AppBundle\Repository;

/**
 * DueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DueRepository extends \Doctrine\ORM\EntityRepository
{
}
